# Generated by Django 4.2 on 2023-06-04 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='dept_manager',
        ),
        migrations.RemoveField(
            model_name='department',
            name='parksites',
        ),
        migrations.RemoveField(
            model_name='parksite',
            name='site_manager',
        ),
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Parksite',
        ),
    ]
