# Generated by Django 4.1.3 on 2023-03-10 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IPDC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Mx.', 'Mx.'), ('Miss', 'Miss'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.')], default=1, max_length=300),
        ),
        migrations.CreateModel(
            name='DomesticRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_of_investment', models.CharField(max_length=300)),
                ('requested_type', models.CharField(choices=[('License', 'License'), ('Land Request', 'Land Request'), ('Expansion', 'Expansion')], max_length=300)),
                ('requested_land', models.FloatField()),
                ('sector', models.CharField(choices=[('Manufacturing', 'Manufacturing'), ('Agriculture', 'Agriculture'), ('Service', 'Service')], max_length=300)),
                ('project_name', models.CharField(max_length=300)),
                ('project_description', models.TextField(max_length=300)),
                ('capital', models.FloatField()),
                ('owner_equity', models.FloatField()),
                ('bank_loan', models.FloatField()),
                ('temporay_job', models.CharField(max_length=300)),
                ('Permanent_job', models.CharField(max_length=300)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPDC.investor')),
            ],
        ),
    ]
