# Generated by Django 4.2 on 2023-05-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPDC', '0003_alter_domesticrequest_form_of_investment_fileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='domesticrequest',
            name='bank_statement',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='domesticrequest',
            name='proposal',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='investor',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='investor',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='FileInfo',
        ),
    ]
