# Generated by Django 4.2 on 2023-05-11 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IPDC', '0004_domesticrequest_bank_statement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privatechat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('secondary_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('primary_user', 'secondary_user')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(max_length=1000000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('filee', models.FileField(blank=True, null=True, upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('privatechat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPDC.privatechat')),
                ('written_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
