# Generated by Django 4.2 on 2023-05-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPDC', '0008_notification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='domesticrequest',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
