# Generated by Django 4.2 on 2023-05-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPDC', '0009_domesticrequest_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domesticrequest',
            name='date',
        ),
        migrations.AddField(
            model_name='domesticrequest',
            name='primary_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domesticrequest',
            name='secondary_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domesticrequest',
            name='status',
            field=models.CharField(choices=[('onlist', 'onlist'), ('pending', 'pending'), ('approved', 'approved'), ('denied', 'denied')], default='onlist', max_length=300),
        ),
        migrations.AddField(
            model_name='domesticrequest',
            name='tertiary_checked',
            field=models.BooleanField(default=False),
        ),
    ]
