# Generated by Django 4.2 on 2023-05-23 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IPDC', '0011_domesticrequest_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField(max_length=1234567)),
                ('allow_investor_to_see', models.BooleanField(default=True)),
                ('domesticrequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPDC.domesticrequest')),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
