# Generated by Django 4.2 on 2023-05-26 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IPDC', '0013_richtext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_text',
        ),
    ]
