# Generated by Django 4.2 on 2023-05-26 07:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IPDC', '0014_remove_feedback_feedback_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
