# Generated by Django 3.2.19 on 2023-05-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPDC', '0015_feedback_feedback_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domesticrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('onlist', 'onlist'), ('pending', 'pending'), ('approved', 'approved'), ('denied', 'denied')], default='onlist', max_length=300),
        ),
    ]
