# Generated by Django 4.2 on 2023-06-04 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IPDC', '0016_alter_domesticrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parksite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('site_manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=300)),
                ('dept_manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parksite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPDC.parksite')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_title', models.CharField(max_length=300)),
                ('case_txt', models.TextField(blank=True, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPDC.department')),
            ],
        ),
    ]
